name: Testing Workflow CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/workflow-B.yml                                           
    with:
      username: mona
